# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQtWidgets/RedactTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RedactTabWidget(object):
    def setupUi(self, RedactTabWidget):
        RedactTabWidget.setObjectName("RedactTabWidget")
        RedactTabWidget.resize(526, 547)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(RedactTabWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 60, 422, 163))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.mainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.selectFileLayout = QtWidgets.QHBoxLayout()
        self.selectFileLayout.setObjectName("selectFileLayout")
        self.SelectedFileLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.SelectedFileLabel.setObjectName("SelectedFileLabel")
        self.selectFileLayout.addWidget(self.SelectedFileLabel)
        self.SelecFileButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.SelecFileButton.setObjectName("SelecFileButton")
        self.selectFileLayout.addWidget(self.SelecFileButton)
        self.mainLayout.addLayout(self.selectFileLayout)
        self.VolumeAndTrimLayout = QtWidgets.QHBoxLayout()
        self.VolumeAndTrimLayout.setObjectName("VolumeAndTrimLayout")
        self.VSliderLayout = QtWidgets.QVBoxLayout()
        self.VSliderLayout.setObjectName("VSliderLayout")
        self.HSliderLayout = QtWidgets.QHBoxLayout()
        self.HSliderLayout.setObjectName("HSliderLayout")
        self.minSliderVolume = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.minSliderVolume.setObjectName("minSliderVolume")
        self.HSliderLayout.addWidget(self.minSliderVolume)
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider.setMouseTracking(False)
        self.horizontalSlider.setMinimum(-100)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(20)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.HSliderLayout.addWidget(self.horizontalSlider)
        self.maxSliderVolume = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.maxSliderVolume.setObjectName("maxSliderVolume")
        self.HSliderLayout.addWidget(self.maxSliderVolume)
        self.VSliderLayout.addLayout(self.HSliderLayout)
        self.SliderVolumeChange = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.SliderVolumeChange.setObjectName("SliderVolumeChange")
        self.VSliderLayout.addWidget(self.SliderVolumeChange)
        self.VolumeAndTrimLayout.addLayout(self.VSliderLayout)
        self.mainLayout.addLayout(self.VolumeAndTrimLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.mainLayout.addLayout(self.horizontalLayout)
        self.PlayAndSaveLayout = QtWidgets.QHBoxLayout()
        self.PlayAndSaveLayout.setObjectName("PlayAndSaveLayout")
        self.SaveButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.SaveButton.setObjectName("SaveButton")
        self.PlayAndSaveLayout.addWidget(self.SaveButton)
        self.PlayButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.PlayButton.setObjectName("PlayButton")
        self.PlayAndSaveLayout.addWidget(self.PlayButton)
        self.mainLayout.addLayout(self.PlayAndSaveLayout)

        self.retranslateUi(RedactTabWidget)
        QtCore.QMetaObject.connectSlotsByName(RedactTabWidget)

    def retranslateUi(self, RedactTabWidget):
        _translate = QtCore.QCoreApplication.translate
        RedactTabWidget.setWindowTitle(_translate("RedactTabWidget", "Form"))
        self.SelectedFileLabel.setText(_translate("RedactTabWidget", "Выберите аудиофайл"))
        self.SelecFileButton.setText(_translate("RedactTabWidget", "Выбрать аудиофайл"))
        self.minSliderVolume.setText(_translate("RedactTabWidget", "-100 дБ"))
        self.maxSliderVolume.setText(_translate("RedactTabWidget", "100 дБ"))
        self.SliderVolumeChange.setText(_translate("RedactTabWidget", "Изменение громкости на: 0 дБ"))
        self.SaveButton.setText(_translate("RedactTabWidget", "Прослушать трек"))
        self.PlayButton.setText(_translate("RedactTabWidget", "Сохранить трек"))
